# Redis 从节点配置（6380）
port 6380
bind 127.0.0.1
protected-mode yes
daemonize no
dir "D:\\BaiduNetdiskDownload\\heima-dianping\\hm-dianping\\deploy\\redis\\6380"
logfile "6380.log"
appendonly yes
appendfilename "appendonly.aof"
# 指定主节点

