# Redis 主节点配置
port 6379
bind 127.0.0.1
protected-mode yes
daemonize no
dir "D:/BaiduNetdiskDownload/heima-dianping/hm-dianping/deploy/redis/6379"
logfile "6379.log"
appendonly yes
appendfilename "appendonly.aof"
