# Redis 从节点配置（6381）
port 6381
bind 127.0.0.1
protected-mode yes
daemonize no
dir "D:\\BaiduNetdiskDownload\\heima-dianping\\hm-dianping\\deploy\\redis\\6381"
logfile "6381.log"
appendonly yes
appendfilename "appendonly.aof"
# 指定主节点
slaveof 127.0.0.1 6380
